CARTE = 1
SPECIAL = 3
CHEF_SPECIAL = 5

SASHIMI = 21
NIGIRI_CHEF = 23
HAND_ROLL_CHEF = 25
USELESS_SPECIAL = 31

COMBO_SPECIALS_LIST = [SASHIMI, NIGIRI_CHEF, HAND_ROLL_CHEF]
SUSHI_CHEF_SPECIAL_GROUPS = [NIGIRI_CHEF, HAND_ROLL_CHEF]
CARTE_MAX = 10